name: what_to_watch
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  lottie: ^2.7.0
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.2.5
  http: ^1.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.1

  # Uygulama adını değiştirmek için
  rename_app: ^1.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/questions/
    - assets/animations/
    - .env
